swagger: "2.0"
info:
  version: "1.0.0"
  title: SixSense Cloud API - vehicle data simulation EXTERNAL
  license:
    name:  Huf Proprietary
  description: |

      ![Brand Logo](./images/sixsense.png)

      ![States Image](./images/pic_external.jpg)

      # Purpose of the vehicle data simulation API

        The SixSense Cloud API allows access to all sorts of vehicle related data, e.g. fuel level, odometer and position.

        If no real data is available (e.g. for virtual devices or real devices that are not connected to a vehicle and have no GPS reception to retrieve the position), a data simulation can be enabled and disabled through this API.

        The simulated data can be accessed through both the GET routes and via subscribing for the data.

        This makes vehicle data related development and testing easier.

      # Changelog

      ## 1.0.0
        Initial version.

      # Mandatory/optional fields
        - In this specification, all mandatory data fields are marked with a red asterisk character ('*').
        - All other data fields are optional.

      # HTTP Status Codes:

        - Unknown event types are accepted by the event handler and 200 is returned. But they will not be processed as no receiver has subscribed to the event type.
        - Known event type with not matching payload is accepted by the event handler and 200 is returned. But the receiver which has subscribed to the event type will generate an error event due to the broken payload.
        - In case 40x HTTP errors are returned, the response body is empty (no correlation ID is returned).

      | Http Code | Description | Information |
      | :---         |     :---      |     :---      |
      | 200 | Success | |
      | 400 | Bad Request | |
      | 401 | Unauthorized | |
      | 403 | Forbidden - Client identified by certificate not authorized to call this request | |
      | 404 | Not Found - externalVehicleRef not found or route suffixed with unknown resource | |
      | 500 | Internal Server Error | |
      | 503 | Service Unavailable | |

host: HOST:PORT
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

#PATHS

paths:

## Events

  /events - huf.vehicleDataSimulationEnabledFailed:
    $ref: "./definitions/paths/events_vehicle_data_simulation_enabled_failed.yaml"

  /events - huf.vehicleDataSimulationDisabledFailed:
    $ref: "./definitions/paths/events_vehicle_data_simulation_disabled_failed.yaml"

definitions:

# Event types

  vehicleDataSimulationEnabledFailed:
    $ref: "./definitions/events/vehicleDataSimulationEnabledFailed.yaml"

  vehicleDataSimulationDisabledFailed:
    $ref: "./definitions/events/vehicleDataSimulationDisabledFailed.yaml"

# Models

  vehicleDataSimulationEnabledFailedPayload:
    $ref: "./definitions/models/vehicleDataSimulationEnabledFailedPayload.yaml"

  vehicleDataSimulationDisabledFailedPayload:
    $ref: "./definitions/models/vehicleDataSimulationDisabledFailedPayload.yaml"

# Responses

  eventResponse:
      $ref: "./definitions/responses/eventResponse.yaml"
