swagger: "2.0"
info:
  version: "1.0.0"
  title: SixSense Cloud API - accounts EXTERNAL
  license:
    name:  Huf Proprietary
  description: |

      ![Brand Logo](./images/sixsense.png)

      ![States Image](./images/pic_external.jpg)

      # Deprecated

        This API shall be considered only as temporary solution. Once a proper idendity and access management (IAM) feature is available, this will not be supported anymore with the next major API update.

      # Purpose of the accounts API

        This API provides a simple interface to create accounts (username/password) that can be used for login procedures, e.g. in the Huf Service App.

      # Failure details

        Since the events in this API contain personal data, the corresponding Failed events do not contain failure details (which would include the personal data). The Failed events do contain an expressive failure reason.

      # Changelog

      ## 0.0.1
        Initial draft for review.

      # Mandatory/optional fields
        - In this specification, all mandatory data fields are marked with a red asterisk character ('*').
        - All other data fields are optional.

      # HTTP Status Codes:

        - Unknown event types are accepted by the event handler and 200 is returned. But they will not be processed as no receiver has subscribed to the event type.
        - Known event type with not matching payload is accepted by the event handler and 200 is returned. But the receiver which has subscribed to the event type will generate an error event due to the broken payload.
        - In case 40x HTTP errors are returned, the response body is empty (no correlation ID is returned).

      | Http Code | Description | Information |
      | :---         |     :---      |     :---      |
      | 200 | Success | |
      | 400 | Bad Request | |
      | 401 | Unauthorized | |
      | 403 | Forbidden - Client identified by certificate not authorized to call this request | |
      | 404 | Not Found - externalVehicleRef not found or route suffixed with unknown resource | |
      | 500 | Internal Server Error | |
      | 503 | Service Unavailable | |

host: HOST:PORT
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

#PATHS

paths:

## Events

  /events - huf.userAccountWithPwCreatedFailed:
    $ref: "./definitions/paths/events_user_account_with_pw_created_failed.yaml"

  /events - huf.userAccountDeletedFailed:
    $ref: "./definitions/paths/events_user_account_deleted_failed.yaml"

  /events - huf.userPasswordUpdatedFailed:
    $ref: "./definitions/paths/events_user_password_updated_failed.yaml"

definitions:

# Event types

  userAccountWithPwCreatedFailed:
    $ref: "./definitions/events/userAccountWithPwCreatedFailed.yaml"

  userAccountDeletedFailed:
    $ref: "./definitions/events/userAccountDeletedFailed.yaml"

  userPasswordUpdatedFailed:
    $ref: "./definitions/events/userPasswordUpdatedFailed.yaml"

# Models

  userAccountWithPwCreatedFailedPayload:
    $ref: "./definitions/models/userAccountWithPwCreatedFailedPayload.yaml"

  userAccountDeletedFailedPayload:
    $ref: "./definitions/models/userAccountDeletedFailedPayload.yaml"

  userPasswordUpdatedFailedPayload:
    $ref: "./definitions/models/userPasswordUpdatedFailedPayload.yaml"

# Responses

  eventResponse:
    $ref: "./definitions/responses/eventResponse.yaml"
