swagger: "2.0"
info:
  title: Huf SixSense Cloud APIs
  description: |

      ![Brand Logo](./images/sixsense.png)

      You are viewing the Huf Cloud API version 1.0.1

      ---

      # generic API requirements

      ## 1.0.0

      [generic API requirements](./index_generic_api_requirements_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # vehicle access

      ## 1.4.0 (under development)

      [vehicle access HUF](./index_vehicle_access_HSM_140.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.3.0

      [vehicle access HUF](./index_vehicle_access_HSM_130.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [vehicle access EXTERNAL](./index_vehicle_access_EXTERNAL_130.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.2.0

      [vehicle access HUF](./index_vehicle_access_HSM_120.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [vehicle access EXTERNAL](./index_vehicle_access_EXTERNAL_120.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.1.1

      [vehicle access HUF](./index_vehicle_access_HSM_111.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [vehicle access EXTERNAL](./index_vehicle_access_EXTERNAL_111.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.1.0

      [vehicle access HUF](./index_vehicle_access_HSM_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [vehicle access EXTERNAL](./index_vehicle_access_EXTERNAL_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.0.1

      [vehicle access HSM](./index_vehicle_access_HSM_101.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [vehicle access EXTERNAL](./index_vehicle_access_EXTERNAL_101.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # vehicle status

      ## 1.1.0

      [vehicle status HUF](./index_vehicle_status_HSM_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.0.0

      [vehicle status HUF](./index_vehicle_status_HSM_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      # status elements

      ## 1.2.0 (under development)

      [status elements](./index_status_elements_120.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.1.0

      [status elements](./index_status_elements_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.0.0

      [status elements](./index_status_elements_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # vehicle telematics

      ## 1.0.0

      [vehicle telematics HUF](./index_vehicle_telematics_HSM.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # broker

      ## 1.0.0

      [broker HUF](./index_broker_HUF_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # remote vehicle access

      ## 1.0.0

      [remote vehicle access HUF](./index_remote_vehicle_access_HUF_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # data subscription

      ## NOT IMPLEMENTED - UNDER DEVELOPMENT

      ## 1.0.0

      [data subscription HUF](./data_subscribed_HUF_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [data subscription EXTERNAL](./data_subscribed_EXTERNAL_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # vehicle master data

      # DEPRECATED

      ## The vehicle master data API is deprecated and will not be supported in future as specified here. Transfer of vehicle master data from customers to Huf is currently done via Excel templates. A new API will be specified and supported when actual demand exists.

      ## 1.3.0

      [vehicle master data HUF](./index_vehicle_master_data_HSM_130.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.2.0

      [vehicle master data HUF](./index_vehicle_master_data_HSM_120.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.1.0

      [vehicle master data HUF](./index_vehicle_master_data_HSM_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [vehicle master data EXTERNAL](./index_vehicle_master_data_EXTERNAL_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.0.0

      [vehicle master data HUF](./index_vehicle_master_data_HSM_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [vehicle master data EXTERNAL](./index_vehicle_master_data_EXTERNAL_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ---

      # accounts

      # DEPRECATED

      ## The accounts API is deprecated and will not anymore be supported as specified here. Account management will be performed by Huf customer support and later by giving Thingsboard access to customers so they can manage their own accounts.

      ## 1.1.0

      [accounts HUF](./index_accounts_HUF_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [accounts EXTERNAL](./index_accounts_EXTERNAL_110.html?defaultModelRendering=model&defaultModelExpandDepth=5)

      ## 1.0.0

      [accounts HUF](./index_accounts_HUF_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)
      [accounts EXTERNAL](./index_accounts_EXTERNAL_100.html?defaultModelRendering=model&defaultModelExpandDepth=5)
