openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Broker API
  license:
    name:  Huf Proprietary
  contact:
    email: support@huf-sixsense.com
  description: |

      ![Brand Logo](./images/sixsense.png)

      ![States Image](./broker_HUF_100/definitions/broker.png)

      ## Broker API - TACS Keyring distribution

      ### Changelog

      #### 1.0.0
        - Released broker API.

      #### 0.1.0
        - get a keyring by using ```GET /keyrings/```
        - check applications health status via ```GET /api/healthz```

      ### General API information
      consumes:
        - application/json
      produces:
        - application/json

#PATHS
paths:

## Keyring
  /api/keyrings:
    $ref: "./definitions/paths/keyrings.yaml"

## Health
# used for internal healthcheck (kubernetes healthcheck)
  /api/healthz:
    $ref: "./definitions/paths/healthz.yaml"
