swagger: "2.0"
info:
  version: "1.0.0"
  title: SixSense Cloud API - vehicle data simulation HUF
  license:
    name:  Huf Proprietary
  description: |

      ![Brand Logo](./images/sixsense.png)

      ![States Image](./images/pic_huf.jpg)

      # Purpose of the vehicle data simulation API

        The SixSense Cloud API allows access to all sorts of vehicle related data, e.g. fuel level, odometer and position.

        If no real data is available (e.g. for virtual devices or real devices that are not connected to a vehicle and have no GPS reception to retrieve the position), a data simulation can be enabled and disabled through this API.

        The simulated data can be accessed through both the GET routes and via subscribing for the data.

        This makes vehicle data related development and testing easier.

      # Changelog

      ## 1.0.0
        Initial version.

      # Mandatory/optional fields
        - In this specification, all mandatory data fields are marked with a red asterisk character ('*').
        - All other data fields are optional.

      # HTTP Status Codes:

        - Unknown event types are accepted by the event handler and 200 is returned. But they will not be processed as no receiver has subscribed to the event type.
        - Known event type with not matching payload is accepted by the event handler and 200 is returned. But the receiver which has subscribed to the event type will generate an error event due to the broken payload.
        - In case 40x HTTP errors are returned, the response body is empty (no correlation ID is returned).

      | Http Code | Description | Information |
      | :---         |     :---      |     :---      |
      | 200 | Success | |
      | 400 | Bad Request | |
      | 401 | Unauthorized | |
      | 403 | Forbidden - Client identified by certificate not authorized to call this request | |
      | 404 | Not Found - externalVehicleRef not found or route suffixed with unknown resource | |
      | 500 | Internal Server Error | |
      | 503 | Service Unavailable | |

      # Failure handling

        This section specifies under which circumstances the EXTERNAL devices API shall trigger failure events.
        This specification does not include failures that are already handled by the Event Handler and notified via HTTP error codes.
        So this speciifcation assumes that the generic structure of the received event is correct and the event payload is at least correct JSON.
        In case more than one failure occurs in the same event, only the first detected failure is reported.
        The failure reason field contains a string that describes the failure cause.

      ## Format failures

      In case of mismatches with the specified event format, the failure reasons are not specified in detail, as they may be provided by a validation library. Exact failure reason strings may change when changing or updating such a library.

      If there is a format failure in an "Event", the resulting failure event shall be of type "EventFailed".

      ## Processing failures

      For events with correct format, failures can still occur while processing the event. This table lists the failure reasons for the applicable processing failures.

      | Event sent to HUF API          | Issue                                                  | Resulting failure event              | Failure reason | Comment
      |--------------------------------|--------------------------------------------------------|------------------------|------------------------------|--------------
      | huf.vehicleDataSimulationEnabled          | externalVehicleRef not found        | huf.vehicleDataSimulationEnabledFailed | "externalVehicleRef not found for given tenant (vehicle not commissioned)" | The actual tenantId and externalVehicleRef is captured in the failure details.
      | huf.vehicleDataSimulationEnabled          | internal processing error        | huf.vehicleDataSimulationEnabledFailed | "internal processing error" |
      | huf.vehicleDataSimulationDisabled          | externalVehicleRef not found        | huf.vehicleDataSimulationDisabledFailed | "externalVehicleRef not found for given tenant (vehicle not commissioned)" | The actual tenantId and externalVehicleRef is captured in the failure details.
      | huf.vehicleDataSimulationDisabled          | internal processing error        | huf.vehicleDataSimulationDisabledFailed | "internal processing error" |

      ## Note
      Enabling the simulation for a vehicle when it is already enabled or disabling when it is already disabled is not regarded as failure and the event is simply ignored.

host: HOST:PORT
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

#PATHS

paths:

## Events

  /events - huf.vehicleDataSimulationEnabled:
    $ref: "./definitions/paths/events_vehicle_data_simulation_enabled.yaml"

  /events - huf.vehicleDataSimulationDisabled:
    $ref: "./definitions/paths/events_vehicle_data_simulation_disabled.yaml"

definitions:

# Event types

  vehicleDataSimulationEnabled:
    $ref: "./definitions/events/vehicleDataSimulationEnabled.yaml"

  vehicleDataSimulationDisabled:
    $ref: "./definitions/events/vehicleDataSimulationDisabled.yaml"

# Models

  vehicleDataSimulationEnabledPayload:
    $ref: "./definitions/models/vehicleDataSimulationEnabledPayload.yaml"

  vehicleDataSimulationDisabledPayload:
    $ref: "./definitions/models/vehicleDataSimulationDisabledPayload.yaml"

# Responses

  eventResponse:
      $ref: "./definitions/responses/eventResponse.yaml"
