swagger: "2.0"
info:
  contact:
    email: support@huf-sixsense.com
  description: |
      ___
      ![States Image](./apis/sixsense.png)
      # Huf Secure Mobile APIs
      ___
      To make sure that you see all changes:
        - please hard reload your browser
        - disable cache or delete the cache before loading the page
        - use incognito window to view page
      ---
      # [Huf Broker API](./broker_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)
      ---
      # [Huf GRAPI](./grapi_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)
      ---
      # [Huf Remote Vehicle Access API](./rvac_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)
      ---
      # [Huf B2B API](./b2b_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)
      ---
      # [Liberkee Voucher API](./liberkee-voucher-api_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)
      ---
      # Draft:
      # [Huf Vehicle & Location Management API](./vehicle-mgmt-api_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)
      ---



