swagger: "2.0"
info:
  contact:
    email: support@huf-sixsense.com
  description: |
      ___
      # Huf Secure Mobile APIs
      ___
      ___
      To make sure that you see all changes, please hard reload your browser (disable cache) or delete the cache before loading the specs.

      ---
      ---
      ![States Image](./hsm_apis/broker.png)
      # Huf Broker API - TACS keyring distribution

      [Huf Broker API](./broker_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)

      ---
      ---
      ![States Image](./hsm_apis/grapi.png)
      # Huf Bluebird Middleware API

      [Huf GRAPI](./grapi_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)

      ---
      ---
      ![States Image](./hsm_apis/rvac.png)
      # Huf Remote Vehicle Access API

      [Huf Remote Vehicle Access API](./rvac_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)

      ---
      ---
      ![States Image](./hsm_apis/b2b.png)
      # Huf B2B API

      [Huf B2B API](./b2b_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)

      ---
      ---
      ![States Image](./hsm_apis/vmgmt.png)
      # Huf Vehicle & Location Management API

      [Huf Vehicle & Location Management API](./vehicle-mgmt-api_index.html?defaultModelRendering=model&defaultModelExpandDepth=8)
