openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Generic Rental API
  license:
    name:  Huf Proprietary
  contact:
    email: support@huf-sixsense.com
  description: |
    ![States Image](./api_spec/v1.0.0_grapi/definitions/grapi.png)

    ![Sequence Diagram](./api_spec/v1.0.0_grapi/definitions/grapi_booking_sequence.png)

    ## Huf - 3rd Party Booking System Middleware API Documentation
    The Generic Rental API (GRAPI) is a middleware for external online travel agency platforms and car rental booking systems provided by Huf Secure Mobile (HSM).",

    ### Supported 3rd Party Booking Systems
    - Bluebird Rentworks

    ### Changelog

    #### 1.0.1
      - add product description to this API documentation
      - add damage report image to `precheckout` example response
      - use acriss codes in example requests and responses
      - remove unused `iataCode`

    #### 1.0.0
      - change attribute name `parkingLocation` to `returnLocation` on check-in
      - add `platformBookingReferenceId` as a custom
      - attach damage report image to pre-checkout response

    #### 0.3.0
      - update driver details by using ```POST /api/bookings/:rentalBookingId/driver```

    #### 0.2.0
      - Add Multicustomer handling/routing support

    #### 0.1.0
      - rename ```externalBookingId``` to ```rentalBookingId```

    #### 0.0.1
      - get quotes by using ```POST /api/quote```
      - retrieve all station locations with ```GET /api/locations```
      - make a reservation by using ```POST /api/bookings/reserve```
      - retrieve all your bookings with ```GET /api/bookings```
      - retrieve a specific booking by id with ```GET /api/bookings/:externalBookingId```
      - cancel a reservation with ```POST /api/bookings/:externalBookingId/cancel```
      - execute precheckout to get vehicle informations by using ```POST /api/bookings/:externalBookingId/precheckout```
      - report damages with ```POST /api/bookings/{:externalBookingId}/damagereport```
      - execute checkout by using ```POST /api/bookings/:externalBookingId/checkout```
      - execute checkin by using ```POST /api/bookings/:externalBookingId/checkin```

    ### General API information
    consumes:
      - application/json

    produces:
      - application/json

#PATHS
paths:

## Quote
  /api/quote:
    $ref: "./definitions/paths/quote.yaml"

## Bookings
  /api/bookings:
    $ref: "./definitions/paths/bookings.yaml"
  /api/bookings/{rentalBookingId}:
    $ref: "./definitions/paths/bookingsRentalBookingId.yaml"
  /api/bookings/reserve:
    $ref: "./definitions/paths/bookingsReserve.yaml"
  /api/bookings/{rentalBookingId}/precheckout:
    $ref: "./definitions/paths/bookingsRentalBookingIdPrecheckout.yaml"
  /api/bookings/{rentalBookingId}/damagereport:
    $ref: "./definitions/paths/bookingsRentalBookingIdDamageReport.yaml"
  /api/bookings/{rentalBookingId}/checkout:
    $ref: "./definitions/paths/bookingsRentalBookingIdCheckout.yaml"
  /api/bookings/{rentalBookingId}/checkin:
    $ref: "./definitions/paths/bookingsRentalBookingIdCheckin.yaml"
  /api/bookings/{rentalBookingId}/cancel:
    $ref: "./definitions/paths/bookingsRentalBookingIdCancel.yaml"
  /api/bookings/{rentalBookingId}/driver:
    $ref: "./definitions/paths/bookingsRentalBookingIdDriver.yaml"

## Locations
  /api/locations:
    $ref: "./definitions/paths/locations.yaml"

## Events
# used for internal tests
  /api/healthcheck:
    $ref: "./definitions/paths/healthcheck.yaml"
