openapi: "3.0.0"
info:
  version: "0.1.0"
  title: Remote vehicle access API
  license:
    name:  Huf Proprietary
  contact:
    email: support@huf-sixsense.com
  description: |
      ![States Image](./v0.1.0_remoteVehicleAccessAPI/definitions/broker.png)

      # Purpose of the remote vehicle access API

        - This API allows to remotely operate the vehicle access functions:
          - lock doors
          - unlock doors
          - enable engine start
          - disable engine start

      ### Changelog

      #### 0.1.0
        - Remotely operate vehicle functions (lock, unlock, mobilize, immobilize). ```POST /api/v1/commands/```
        - check applications health status via ```GET /api/v1/healthz```

      ### General API information
      consumes:
        - application/json
      produces:
        - application/json

#PATHS
paths:

## Keyring
  /api/v1/commands:
    $ref: "./definitions/paths/commands.yaml"

## Health
# used for internal healthcheck (kubernetes healthcheck)
  /api/v1/healthz:
    $ref: "./definitions/paths/healthz.yaml"
